openapi: 3.0.0
info:
  title: Health Check Service
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: Health
    description: Health and status related endpoints

paths:
  /health:
    get:
      security:
        - BearerAuth: []
      tags:
        - Health
      summary: Health Check Endpoint
      description: >
        This endpoint provides a health check for the service. It can be used to monitor the status and availability of the service. The endpoint checks various internal parameters to ensure the service is operational, and returns a status indicating the health.
      operationId: api.health.health_check
      responses:
        '200':
          description: Service is healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '500':
          description: Internal Server Error - Service is unhealthy or encountered an unexpected condition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              msg:
                type: string
                example: Missing or invalid token
  schemas:
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          enum: [healthy]
          description: Indicates that the service is operational and healthy.
    HealthError:
      type: object
      properties:
        status:
          type: string
          enum: [unhealthy]
          description: Indicates that the service is not operational and unhealthy.
        error:
          type: string
          description: A detailed error message explaining the reason for the service's unhealthy state.
